
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      platform: postgres
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PW}
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${EMAIL_FROM}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: ${SMTP_CONNECTION_TIMEOUT}
          timeout: ${SMTP_TIMEOUT}
          writetimeout: ${SMTP_WRITE_TIMEOUT}
      auth-code-expiration-millis: ${SMTP_AUTH_CODE_EXPIRATION}
logging:
  level:
    org.springframework.security: DEBUG


jwt:
  header: Authorization
  secret: ${TOKEN_SECRET}
  accessTokenExpiresIn: ${ACCESSTOKEN_VALIDTIME}
  refreshTokenExpiresIn: ${REFRESHTOKEN_VALIDTIME}