
spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      platform: postgres
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PW}
logging:
  level:
    org.springframework.security: DEBUG


jwt:
  header: Authorization
  secret: ${TOKEN_SECRET}
  accessTokenExpiresIn: ${ACCESSTOKEN_VALIDTIME}
  refreshTokenExpiresIn: ${REFRESHTOKEN_VALIDTIME}